import Vue from 'vue'

export const bus = new Vue()

export const store = {
	state: {
		sessionUID: '',
		step: 'usertype',
		userNeedOrga: false,
		user: {
			gender: '',
			taxCountry: '',
			birthday: {
				day: '',
				month: '',
				year: '',
				city: '',
				district: '',
				department: '',
				country: '',
				nationality: ''
			},
			address: {
				number: '',
				numberComp: '',
				street: '',
				postalCode: '',
				city: '',
				country: ''
			},
			notification: '',
			phone: {
				code: '',
				number: ''
			},
			language: ''
		},
		organization: {
			apiId: '',
			name: '',
			activity: '',
			idnumber: '',
			email: '',
			website: '',
			legalform: '',
			apecode: '',
			capital: '',
			legaltown: '',
			representativefunction: '',
			address: {
				number: '',
				numberComp: '',
				street: '',
				postalCode: '',
				city: '',
				country: ''
			}
		}
	},
	props: {
		ajaxurl: '',
		customajaxurl: '',
		initFileList: [],
		capacities: []
	},
	static: {
		addressNumberComp: [
			{ Id: '', Text: '' },
			{ Id: 'bis', Text: 'bis' },
			{ Id: 'ter', Text: 'ter' },
			{ Id: 'quater', Text: 'quater' },
			{ Id: 'quinquies', Text: 'quinquies' }
		],
		frenchDepartments: [
			{ Id: '', Text: '' },
			{ Id: '01', Text: 'Ain' },
			{ Id: '02', Text: 'Aisne' },
			{ Id: '03', Text: 'Allier' },
			{ Id: '04', Text: 'Alpes-de-Haute-Provence' },
			{ Id: '05', Text: 'Hautes-Alpes' },
			{ Id: '06', Text: 'Alpes-Maritimes' },
			{ Id: '07', Text: 'Ardèche' },
			{ Id: '08', Text: 'Ardennes' },
			{ Id: '09', Text: 'Ariège' },
			{ Id: '10', Text: 'Aube' },
			{ Id: '11', Text: 'Aude' },
			{ Id: '12', Text: 'Aveyron' },
			{ Id: '13', Text: 'Bouches-du-Rhône' },
			{ Id: '14', Text: 'Calvados' },
			{ Id: '15', Text: 'Cantal' },
			{ Id: '16', Text: 'Charente' },
			{ Id: '17', Text: 'Charente-Maritime' },
			{ Id: '18', Text: 'Cher' },
			{ Id: '19', Text: 'Corrèze' },
			{ Id: '2A', Text: 'Corse-du-Sud' },
			{ Id: '2B', Text: 'Haute-Corse' },
			{ Id: '21', Text: 'Côte-d\'Or' },
			{ Id: '22', Text: 'Côtes d\'Armor' },
			{ Id: '23', Text: 'Creuse' },
			{ Id: '24', Text: 'Dordogne' },
			{ Id: '25', Text: 'Doubs' },
			{ Id: '26', Text: 'Drôme' },
			{ Id: '27', Text: 'Eure' },
			{ Id: '28', Text: 'Eure-et-Loir' },
			{ Id: '29', Text: 'Finistère' },
			{ Id: '30', Text: 'Gard' },
			{ Id: '31', Text: 'Haute-Garonne' },
			{ Id: '32', Text: 'Gers' },
			{ Id: '33', Text: 'Gironde' },
			{ Id: '34', Text: 'Hérault' },
			{ Id: '35', Text: 'Ille-et-Vilaine' },
			{ Id: '36', Text: 'Indre' },
			{ Id: '37', Text: 'Indre-et-Loire' },
			{ Id: '38', Text: 'Isère' },
			{ Id: '39', Text: 'Jura' },
			{ Id: '40', Text: 'Landes' },
			{ Id: '41', Text: 'Loir-et-Cher' },
			{ Id: '42', Text: 'Loire' },
			{ Id: '43', Text: 'Haute-Loire' },
			{ Id: '44', Text: 'Loire-Atlantique' },
			{ Id: '45', Text: 'Loiret' },
			{ Id: '46', Text: 'Lot' },
			{ Id: '47', Text: 'Lot-et-Garonne' },
			{ Id: '48', Text: 'Lozère' },
			{ Id: '49', Text: 'Maine-et-Loire' },
			{ Id: '50', Text: 'Manche' },
			{ Id: '51', Text: 'Marne' },
			{ Id: '52', Text: 'Haute-Marne' },
			{ Id: '53', Text: 'Mayenne' },
			{ Id: '54', Text: 'Meurthe-et-Moselle' },
			{ Id: '55', Text: 'Meuse' },
			{ Id: '56', Text: 'Morbihan' },
			{ Id: '57', Text: 'Moselle' },
			{ Id: '58', Text: 'Nièvre' },
			{ Id: '59', Text: 'Nord' },
			{ Id: '60', Text: 'Oise' },
			{ Id: '61', Text: 'Orne' },
			{ Id: '62', Text: 'Pas-de-Calais' },
			{ Id: '63', Text: 'Puy-de-Dôme' },
			{ Id: '64', Text: 'Pyrénées-Atlantiques' },
			{ Id: '65', Text: 'Hautes-Pyrénées' },
			{ Id: '66', Text: 'Pyrénées-Orientales' },
			{ Id: '67', Text: 'Bas-Rhin' },
			{ Id: '68', Text: 'Haut-Rhin' },
			{ Id: '69', Text: 'Rhône' },
			{ Id: '70', Text: 'Haute-Saône' },
			{ Id: '71', Text: 'Saône-et-Loire' },
			{ Id: '72', Text: 'Sarthe' },
			{ Id: '73', Text: 'Savoie' },
			{ Id: '74', Text: 'Haute-Savoie' },
			{ Id: '75', Text: 'Paris' },
			{ Id: '76', Text: 'Seine-Maritime' },
			{ Id: '77', Text: 'Seine-et-Marne' },
			{ Id: '78', Text: 'Yvelines' },
			{ Id: '79', Text: 'Deux-Sèvres' },
			{ Id: '80', Text: 'Somme' },
			{ Id: '81', Text: 'Tarn' },
			{ Id: '82', Text: 'Tarn-et-Garonne' },
			{ Id: '83', Text: 'Var' },
			{ Id: '84', Text: 'Vaucluse' },
			{ Id: '85', Text: 'Vendée' },
			{ Id: '86', Text: 'Vienne' },
			{ Id: '87', Text: 'Haute-Vienne' },
			{ Id: '88', Text: 'Vosges' },
			{ Id: '89', Text: 'Yonne' },
			{ Id: '90', Text: 'Territoire de Belfort' },
			{ Id: '91', Text: 'Essonne' },
			{ Id: '92', Text: 'Hauts-de-Seine' },
			{ Id: '93', Text: 'Seine-Saint-Denis' },
			{ Id: '94', Text: 'Val-de-Marne' },
			{ Id: '95', Text: 'Val-d\'Oise' },
			{ Id: '971', Text: 'Guadeloupe' },
			{ Id: '972', Text: 'Martinique' },
			{ Id: '973', Text: 'Guyane' },
			{ Id: '974', Text: 'La Réunion' },
			{ Id: '976', Text: 'Mayotte' },
			{ Id: '98', Text: 'Nouvelle Calédonie' }
		],
		countries: [
			{ Id: '', Text: '' },
			{ Id: 'FR', Text: 'FRANCE' },
			{ Id: 'AF', Text: 'AFGHANISTAN' },
			{ Id: 'AX', Text: 'ÅLAND ISLANDS' },
			{ Id: 'AL', Text: 'ALBANIA' },
			{ Id: 'DZ', Text: 'ALGERIA' },
			{ Id: 'AS', Text: 'AMERICAN SAMOA' },
			{ Id: 'AD', Text: 'ANDORRA' },
			{ Id: 'AO', Text: 'ANGOLA' },
			{ Id: 'AI', Text: 'ANGUILLA' },
			{ Id: 'AQ', Text: 'ANTARCTICA' },
			{ Id: 'AG', Text: 'ANTIGUA AND BARBUDA' },
			{ Id: 'AR', Text: 'ARGENTINA' },
			{ Id: 'AM', Text: 'ARMENIA' },
			{ Id: 'AW', Text: 'ARUBA' },
			{ Id: 'AU', Text: 'AUSTRALIA' },
			{ Id: 'AT', Text: 'AUSTRIA' },
			{ Id: 'AZ', Text: 'AZERBAIJAN' },
			{ Id: 'BS', Text: 'BAHAMAS' },
			{ Id: 'BH', Text: 'BAHRAIN' },
			{ Id: 'BD', Text: 'BANGLADESH' },
			{ Id: 'BB', Text: 'BARBADOS' },
			{ Id: 'BY', Text: 'BELARUS' },
			{ Id: 'BE', Text: 'BELGIUM' },
			{ Id: 'BZ', Text: 'BELIZE' },
			{ Id: 'BJ', Text: 'BENIN' },
			{ Id: 'BM', Text: 'BERMUDA' },
			{ Id: 'BT', Text: 'BHUTAN' },
			{ Id: 'BO', Text: 'BOLIVIA, PLURINATIONAL STATE OF' },
			{ Id: 'BQ', Text: 'BONAIRE, SINT EUSTATIUS AND SABA' },
			{ Id: 'BA', Text: 'BOSNIA AND HERZEGOVINA' },
			{ Id: 'BW', Text: 'BOTSWANA' },
			{ Id: 'BV', Text: 'BOUVET ISLAND' },
			{ Id: 'BR', Text: 'BRAZIL' },
			{ Id: 'IO', Text: 'BRITISH INDIAN OCEAN TERRITORY' },
			{ Id: 'BN', Text: 'BRUNEI DARUSSALAM' },
			{ Id: 'BG', Text: 'BULGARIA' },
			{ Id: 'BF', Text: 'BURKINA FASO' },
			{ Id: 'BI', Text: 'BURUNDI' },
			{ Id: 'KH', Text: 'CAMBODIA' },
			{ Id: 'CM', Text: 'CAMEROON' },
			{ Id: 'CA', Text: 'CANADA' },
			{ Id: 'CV', Text: 'CAPE VERDE' },
			{ Id: 'KY', Text: 'CAYMAN ISLANDS' },
			{ Id: 'CF', Text: 'CENTRAL AFRICAN REPUBLIC' },
			{ Id: 'TD', Text: 'CHAD' },
			{ Id: 'CL', Text: 'CHILE' },
			{ Id: 'CN', Text: 'CHINA' },
			{ Id: 'CX', Text: 'CHRISTMAS ISLAND' },
			{ Id: 'CC', Text: 'COCOS (KEELING) ISLANDS' },
			{ Id: 'CO', Text: 'COLOMBIA' },
			{ Id: 'KM', Text: 'COMOROS' },
			{ Id: 'CG', Text: 'CONGO' },
			{ Id: 'CD', Text: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' },
			{ Id: 'CK', Text: 'COOK ISLANDS' },
			{ Id: 'CR', Text: 'COSTA RICA' },
			{ Id: 'CI', Text: 'CÔTE D\'IVOIRE' },
			{ Id: 'HR', Text: 'CROATIA' },
			{ Id: 'CU', Text: 'CUBA' },
			{ Id: 'CW', Text: 'CURAÇAO' },
			{ Id: 'CY', Text: 'CYPRUS' },
			{ Id: 'CZ', Text: 'CZECH REPUBLIC' },
			{ Id: 'DK', Text: 'DENMARK' },
			{ Id: 'DJ', Text: 'DJIBOUTI' },
			{ Id: 'DM', Text: 'DOMINICA' },
			{ Id: 'DO', Text: 'DOMINICAN REPUBLIC' },
			{ Id: 'EC', Text: 'ECUADOR' },
			{ Id: 'EG', Text: 'EGYPT' },
			{ Id: 'SV', Text: 'EL SALVADOR' },
			{ Id: 'GQ', Text: 'EQUATORIAL GUINEA' },
			{ Id: 'ER', Text: 'ERITREA' },
			{ Id: 'EE', Text: 'ESTONIA' },
			{ Id: 'ET', Text: 'ETHIOPIA' },
			{ Id: 'FK', Text: 'FALKLAND ISLANDS (MALVINAS)' },
			{ Id: 'FO', Text: 'FAROE ISLANDS' },
			{ Id: 'FJ', Text: 'FIJI' },
			{ Id: 'FI', Text: 'FINLAND' },
			{ Id: 'GF', Text: 'FRENCH GUIANA' },
			{ Id: 'PF', Text: 'FRENCH POLYNESIA' },
			{ Id: 'TF', Text: 'FRENCH SOUTHERN TERRITORIES' },
			{ Id: 'GA', Text: 'GABON' },
			{ Id: 'GM', Text: 'GAMBIA' },
			{ Id: 'GE', Text: 'GEORGIA' },
			{ Id: 'DE', Text: 'GERMANY' },
			{ Id: 'GH', Text: 'GHANA' },
			{ Id: 'GI', Text: 'GIBRALTAR' },
			{ Id: 'GR', Text: 'GREECE' },
			{ Id: 'GL', Text: 'GREENLAND' },
			{ Id: 'GD', Text: 'GRENADA' },
			{ Id: 'GP', Text: 'GUADELOUPE' },
			{ Id: 'GU', Text: 'GUAM' },
			{ Id: 'GT', Text: 'GUATEMALA' },
			{ Id: 'GG', Text: 'GUERNSEY' },
			{ Id: 'GN', Text: 'GUINEA' },
			{ Id: 'GW', Text: 'GUINEA-BISSAU' },
			{ Id: 'GY', Text: 'GUYANA' },
			{ Id: 'HT', Text: 'HAITI' },
			{ Id: 'HM', Text: 'HEARD ISLAND AND MCDONALD ISLANDS' },
			{ Id: 'VA', Text: 'HOLY SEE (VATICAN CITY STATE)' },
			{ Id: 'HN', Text: 'HONDURAS' },
			{ Id: 'HK', Text: 'HONG KONG' },
			{ Id: 'HU', Text: 'HUNGARY' },
			{ Id: 'IS', Text: 'ICELAND' },
			{ Id: 'IN', Text: 'INDIA' },
			{ Id: 'ID', Text: 'INDONESIA' },
			{ Id: 'IR', Text: 'IRAN, ISLAMIC REPUBLIC OF' },
			{ Id: 'IQ', Text: 'IRAQ' },
			{ Id: 'IE', Text: 'IRELAND' },
			{ Id: 'IM', Text: 'ISLE OF MAN' },
			{ Id: 'IL', Text: 'ISRAEL' },
			{ Id: 'IT', Text: 'ITALY' },
			{ Id: 'JM', Text: 'JAMAICA' },
			{ Id: 'JP', Text: 'JAPAN' },
			{ Id: 'JE', Text: 'JERSEY' },
			{ Id: 'JO', Text: 'JORDAN' },
			{ Id: 'KZ', Text: 'KAZAKHSTAN' },
			{ Id: 'KE', Text: 'KENYA' },
			{ Id: 'KI', Text: 'KIRIBATI' },
			{ Id: 'KP', Text: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF' },
			{ Id: 'KR', Text: 'KOREA, REPUBLIC OF' },
			{ Id: 'KW', Text: 'KUWAIT' },
			{ Id: 'KG', Text: 'KYRGYZSTAN' },
			{ Id: 'LA', Text: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC' },
			{ Id: 'LV', Text: 'LATVIA' },
			{ Id: 'LB', Text: 'LEBANON' },
			{ Id: 'LS', Text: 'LESOTHO' },
			{ Id: 'LR', Text: 'LIBERIA' },
			{ Id: 'LY', Text: 'LIBYA' },
			{ Id: 'LI', Text: 'LIECHTENSTEIN' },
			{ Id: 'LT', Text: 'LITHUANIA' },
			{ Id: 'LU', Text: 'LUXEMBOURG' },
			{ Id: 'MO', Text: 'MACAO' },
			{ Id: 'MK', Text: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
			{ Id: 'MG', Text: 'MADAGASCAR' },
			{ Id: 'MW', Text: 'MALAWI' },
			{ Id: 'MY', Text: 'MALAYSIA' },
			{ Id: 'MV', Text: 'MALDIVES' },
			{ Id: 'ML', Text: 'MALI' },
			{ Id: 'MT', Text: 'MALTA' },
			{ Id: 'MH', Text: 'MARSHALL ISLANDS' },
			{ Id: 'MQ', Text: 'MARTINIQUE' },
			{ Id: 'MR', Text: 'MAURITANIA' },
			{ Id: 'MU', Text: 'MAURITIUS' },
			{ Id: 'YT', Text: 'MAYOTTE' },
			{ Id: 'MX', Text: 'MEXICO' },
			{ Id: 'FM', Text: 'MICRONESIA, FEDERATED STATES OF' },
			{ Id: 'MD', Text: 'MOLDOVA, REPUBLIC OF' },
			{ Id: 'MC', Text: 'MONACO' },
			{ Id: 'MN', Text: 'MONGOLIA' },
			{ Id: 'ME', Text: 'MONTENEGRO' },
			{ Id: 'MS', Text: 'MONTSERRAT' },
			{ Id: 'MA', Text: 'MOROCCO' },
			{ Id: 'MZ', Text: 'MOZAMBIQUE' },
			{ Id: 'MM', Text: 'MYANMAR' },
			{ Id: 'NA', Text: 'NAMIBIA' },
			{ Id: 'NR', Text: 'NAURU' },
			{ Id: 'NP', Text: 'NEPAL' },
			{ Id: 'NL', Text: 'NETHERLANDS' },
			{ Id: 'NC', Text: 'NEW CALEDONIA' },
			{ Id: 'NZ', Text: 'NEW ZEALAND' },
			{ Id: 'NI', Text: 'NICARAGUA' },
			{ Id: 'NE', Text: 'NIGER' },
			{ Id: 'NG', Text: 'NIGERIA' },
			{ Id: 'NU', Text: 'NIUE' },
			{ Id: 'NF', Text: 'NORFOLK ISLAND' },
			{ Id: 'MP', Text: 'NORTHERN MARIANA ISLANDS' },
			{ Id: 'NO', Text: 'NORWAY' },
			{ Id: 'OM', Text: 'OMAN' },
			{ Id: 'PK', Text: 'PAKISTAN' },
			{ Id: 'PW', Text: 'PALAU' },
			{ Id: 'PS', Text: 'PALESTINE, STATE OF' },
			{ Id: 'PA', Text: 'PANAMA' },
			{ Id: 'PG', Text: 'PAPUA NEW GUINEA' },
			{ Id: 'PY', Text: 'PARAGUAY' },
			{ Id: 'PE', Text: 'PERU' },
			{ Id: 'PH', Text: 'PHILIPPINES' },
			{ Id: 'PN', Text: 'PITCAIRN' },
			{ Id: 'PL', Text: 'POLAND' },
			{ Id: 'PT', Text: 'PORTUGAL' },
			{ Id: 'PR', Text: 'PUERTO RICO' },
			{ Id: 'QA', Text: 'QATAR' },
			{ Id: 'RE', Text: 'RÉUNION' },
			{ Id: 'RO', Text: 'ROMANIA' },
			{ Id: 'RU', Text: 'RUSSIAN FEDERATION' },
			{ Id: 'RW', Text: 'RWANDA' },
			{ Id: 'BL', Text: 'SAINT BARTHÉLEMY' },
			{ Id: 'SH', Text: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA' },
			{ Id: 'KN', Text: 'SAINT KITTS AND NEVIS' },
			{ Id: 'LC', Text: 'SAINT LUCIA' },
			{ Id: 'MF', Text: 'SAINT MARTIN (FRENCH PART)' },
			{ Id: 'PM', Text: 'SAINT PIERRE AND MIQUELON' },
			{ Id: 'VC', Text: 'SAINT VINCENT AND THE GRENADINES' },
			{ Id: 'WS', Text: 'SAMOA' },
			{ Id: 'SM', Text: 'SAN MARINO' },
			{ Id: 'ST', Text: 'SAO TOME AND PRINCIPE' },
			{ Id: 'SA', Text: 'SAUDI ARABIA' },
			{ Id: 'SN', Text: 'SENEGAL' },
			{ Id: 'RS', Text: 'SERBIA' },
			{ Id: 'SC', Text: 'SEYCHELLES' },
			{ Id: 'SL', Text: 'SIERRA LEONE' },
			{ Id: 'SG', Text: 'SINGAPORE' },
			{ Id: 'SX', Text: 'SINT MAARTEN (DUTCH PART)' },
			{ Id: 'SK', Text: 'SLOVAKIA' },
			{ Id: 'SI', Text: 'SLOVENIA' },
			{ Id: 'SB', Text: 'SOLOMON ISLANDS' },
			{ Id: 'SO', Text: 'SOMALIA' },
			{ Id: 'ZA', Text: 'SOUTH AFRICA' },
			{ Id: 'GS', Text: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
			{ Id: 'SS', Text: 'SOUTH SUDAN' },
			{ Id: 'ES', Text: 'SPAIN' },
			{ Id: 'LK', Text: 'SRI LANKA' },
			{ Id: 'SD', Text: 'SUDAN' },
			{ Id: 'SR', Text: 'SURINAME' },
			{ Id: 'SJ', Text: 'SVALBARD AND JAN MAYEN' },
			{ Id: 'SZ', Text: 'SWAZILAND' },
			{ Id: 'SE', Text: 'SWEDEN' },
			{ Id: 'CH', Text: 'SWITZERLAND' },
			{ Id: 'SY', Text: 'SYRIAN ARAB REPUBLIC' },
			{ Id: 'TW', Text: 'TAIWAN, PROVINCE OF CHINA' },
			{ Id: 'TJ', Text: 'TAJIKISTAN' },
			{ Id: 'TZ', Text: 'TANZANIA, UNITED REPUBLIC OF' },
			{ Id: 'TH', Text: 'THAILAND' },
			{ Id: 'TL', Text: 'TIMOR-LESTE' },
			{ Id: 'TG', Text: 'TOGO' },
			{ Id: 'TK', Text: 'TOKELAU' },
			{ Id: 'TO', Text: 'TONGA' },
			{ Id: 'TT', Text: 'TRINIDAD AND TOBAGO' },
			{ Id: 'TN', Text: 'TUNISIA' },
			{ Id: 'TR', Text: 'TURKEY' },
			{ Id: 'TM', Text: 'TURKMENISTAN' },
			{ Id: 'TC', Text: 'TURKS AND CAICOS ISLANDS' },
			{ Id: 'TV', Text: 'TUVALU' },
			{ Id: 'UG', Text: 'UGANDA' },
			{ Id: 'UA', Text: 'UKRAINE' },
			{ Id: 'AE', Text: 'UNITED ARAB EMIRATES' },
			{ Id: 'GB', Text: 'UNITED KINGDOM' },
			{ Id: 'US', Text: 'UNITED STATES' },
			{ Id: 'UM', Text: 'UNITED STATES MINOR OUTLYING ISLANDS' },
			{ Id: 'UY', Text: 'URUGUAY' },
			{ Id: 'UZ', Text: 'UZBEKISTAN' },
			{ Id: 'VU', Text: 'VANUATU' },
			{ Id: 'VE', Text: 'VENEZUELA, BOLIVARIAN REPUBLIC OF' },
			{ Id: 'VN', Text: 'VIET NAM' },
			{ Id: 'VG', Text: 'VIRGIN ISLANDS, BRITISH' },
			{ Id: 'VI', Text: 'VIRGIN ISLANDS, U.S.' },
			{ Id: 'WF', Text: 'WALLIS AND FUTUNA' },
			{ Id: 'EH', Text: 'WESTERN SAHARA' },
			{ Id: 'YE', Text: 'YEMEN' },
			{ Id: 'ZM', Text: 'ZAMBIA' },
			{ Id: 'ZW', Text: 'ZIMBABWE' }
		],
		phoneCodes: [
			{ "dial_code": "", Id: '', Text: '' },
			{ "dial_code": "+33", Id: "FR", Text: "FR"},
			{ "dial_code": "+93", Id: "AF", Text: "AF"},
			{ "dial_code": "+358", Id: "AX", Text: "AX"},
			{ "dial_code": "+355", Id: "AL", Text: "AL"},
			{ "dial_code": "+213", Id: "DZ", Text: "DZ"},
			{ "dial_code": "+1684", Id: "AS", Text: "AS"},
			{ "dial_code": "+376", Id: "AD", Text: "AD"},
			{ "dial_code": "+244", Id: "AO", Text: "AO"},
			{ "dial_code": "+1264", Id: "AI", Text: "AI"},
			{ "dial_code": "+672", Id: "AQ", Text: "AQ"},
			{ "dial_code": "+1268", Id: "AG", Text: "AG"},
			{ "dial_code": "+54", Id: "AR", Text: "AR"},
			{ "dial_code": "+374", Id: "AM", Text: "AM"},
			{ "dial_code": "+297", Id: "AW", Text: "AW"},
			{ "dial_code": "+61", Id: "AU", Text: "AU"},
			{ "dial_code": "+43", Id: "AT", Text: "AT"},
			{ "dial_code": "+994", Id: "AZ", Text: "AZ"},
			{ "dial_code": "+1242", Id: "BS", Text: "BS"},
			{ "dial_code": "+973", Id: "BH", Text: "BH"},
			{ "dial_code": "+880", Id: "BD", Text: "BD"},
			{ "dial_code": "+1246", Id: "BB", Text: "BB"},
			{ "dial_code": "+375", Id: "BY", Text: "BY"},
			{ "dial_code": "+32", Id: "BE", Text: "BE"},
			{ "dial_code": "+501", Id: "BZ", Text: "BZ"},
			{ "dial_code": "+229", Id: "BJ", Text: "BJ"},
			{ "dial_code": "+1441", Id: "BM", Text: "BM"},
			{ "dial_code": "+975", Id: "BT", Text: "BT"},
			{ "dial_code": "+591", Id: "BO", Text: "BO"},
			{ "dial_code": "+387", Id: "BA", Text: "BA"},
			{ "dial_code": "+267", Id: "BW", Text: "BW"},
			{ "dial_code": "+47", Id: "BV", Text: "BV"},
			{ "dial_code": "+55", Id: "BR", Text: "BR"},
			{ "dial_code": "+246", Id: "IO", Text: "IO"},
			{ "dial_code": "+673", Id: "BN", Text: "BN"},
			{ "dial_code": "+359", Id: "BG", Text: "BG"},
			{ "dial_code": "+226", Id: "BF", Text: "BF"},
			{ "dial_code": "+257", Id: "BI", Text: "BI"},
			{ "dial_code": "+855", Id: "KH", Text: "KH"},
			{ "dial_code": "+237", Id: "CM", Text: "CM"},
			{ "dial_code": "+1", Id: "CA", Text: "CA"},
			{ "dial_code": "+238", Id: "CV", Text: "CV"},
			{ "dial_code": "+ 345", Id: "KY", Text: "KY"},
			{ "dial_code": "+236", Id: "CF", Text: "CF"},
			{ "dial_code": "+235", Id: "TD", Text: "TD"},
			{ "dial_code": "+56", Id: "CL", Text: "CL"},
			{ "dial_code": "+86", Id: "CN", Text: "CN"},
			{ "dial_code": "+61", Id: "CX", Text: "CX"},
			{ "dial_code": "+61", Id: "CC", Text: "CC"},
			{ "dial_code": "+57", Id: "CO", Text: "CO"},
			{ "dial_code": "+269", Id: "KM", Text: "KM"},
			{ "dial_code": "+242", Id: "CG", Text: "CG"},
			{ "dial_code": "+243", Id: "CD", Text: "CD"},
			{ "dial_code": "+682", Id: "CK", Text: "CK"},
			{ "dial_code": "+506", Id: "CR", Text: "CR"},
			{ "dial_code": "+225", Id: "CI", Text: "CI"},
			{ "dial_code": "+385", Id: "HR", Text: "HR"},
			{ "dial_code": "+53", Id: "CU", Text: "CU"},
			{ "dial_code": "+357", Id: "CY", Text: "CY"},
			{ "dial_code": "+420", Id: "CZ", Text: "CZ"},
			{ "dial_code": "+45", Id: "DK", Text: "DK"},
			{ "dial_code": "+253", Id: "DJ", Text: "DJ"},
			{ "dial_code": "+1767", Id: "DM", Text: "DM"},
			{ "dial_code": "+1849", Id: "DO", Text: "DO"},
			{ "dial_code": "+593", Id: "EC", Text: "EC"},
			{ "dial_code": "+20", Id: "EG", Text: "EG"},
			{ "dial_code": "+503", Id: "SV", Text: "SV"},
			{ "dial_code": "+240", Id: "GQ", Text: "GQ"},
			{ "dial_code": "+291", Id: "ER", Text: "ER"},
			{ "dial_code": "+372", Id: "EE", Text: "EE"},
			{ "dial_code": "+251", Id: "ET", Text: "ET"},
			{ "dial_code": "+500", Id: "FK", Text: "FK"},
			{ "dial_code": "+298", Id: "FO", Text: "FO"},
			{ "dial_code": "+679", Id: "FJ", Text: "FJ"},
			{ "dial_code": "+358", Id: "FI", Text: "FI"},
			{ "dial_code": "+594", Id: "GF", Text: "GF"},
			{ "dial_code": "+689", Id: "PF", Text: "PF"},
			{ "dial_code": "+262", Id: "TF", Text: "TF"},
			{ "dial_code": "+241", Id: "GA", Text: "GA"},
			{ "dial_code": "+220", Id: "GM", Text: "GM"},
			{ "dial_code": "+995", Id: "GE", Text: "GE"},
			{ "dial_code": "+49", Id: "DE", Text: "DE"},
			{ "dial_code": "+233", Id: "GH", Text: "GH"},
			{ "dial_code": "+350", Id: "GI", Text: "GI"},
			{ "dial_code": "+30", Id: "GR", Text: "GR"},
			{ "dial_code": "+299", Id: "GL", Text: "GL"},
			{ "dial_code": "+1473", Id: "GD", Text: "GD"},
			{ "dial_code": "+590", Id: "GP", Text: "GP"},
			{ "dial_code": "+1671", Id: "GU", Text: "GU"},
			{ "dial_code": "+502", Id: "GT", Text: "GT"},
			{ "dial_code": "+44", Id: "GG", Text: "GG"},
			{ "dial_code": "+224", Id: "GN", Text: "GN"},
			{ "dial_code": "+245", Id: "GW", Text: "GW"},
			{ "dial_code": "+592", Id: "GY", Text: "GY"},
			{ "dial_code": "+509", Id: "HT", Text: "HT"},
			{ "dial_code": "+0", Id: "HM", Text: "HM"},
			{ "dial_code": "+379", Id: "VA", Text: "VA"},
			{ "dial_code": "+504", Id: "HN", Text: "HN"},
			{ "dial_code": "+852", Id: "HK", Text: "HK"},
			{ "dial_code": "+36", Id: "HU", Text: "HU"},
			{ "dial_code": "+354", Id: "IS", Text: "IS"},
			{ "dial_code": "+91", Id: "IN", Text: "IN"},
			{ "dial_code": "+62", Id: "ID", Text: "ID"},
			{ "dial_code": "+98", Id: "IR", Text: "IR"},
			{ "dial_code": "+964", Id: "IQ", Text: "IQ"},
			{ "dial_code": "+353", Id: "IE", Text: "IE"},
			{ "dial_code": "+44", Id: "IM", Text: "IM"},
			{ "dial_code": "+972", Id: "IL", Text: "IL"},
			{ "dial_code": "+39", Id: "IT", Text: "IT"},
			{ "dial_code": "+1876", Id: "JM", Text: "JM"},
			{ "dial_code": "+81", Id: "JP", Text: "JP"},
			{ "dial_code": "+44", Id: "JE", Text: "JE"},
			{ "dial_code": "+962", Id: "JO", Text: "JO"},
			{ "dial_code": "+7", Id: "KZ", Text: "KZ"},
			{ "dial_code": "+254", Id: "KE", Text: "KE"},
			{ "dial_code": "+686", Id: "KI", Text: "KI"},
			{ "dial_code": "+850", Id: "KP", Text: "KP"},
			{ "dial_code": "+82", Id: "KR", Text: "KR"},
			{ "dial_code": "+383", Id: "XK", Text: "XK"},
			{ "dial_code": "+965", Id: "KW", Text: "KW"},
			{ "dial_code": "+996", Id: "KG", Text: "KG"},
			{ "dial_code": "+856", Id: "LA", Text: "LA"},
			{ "dial_code": "+371", Id: "LV", Text: "LV"},
			{ "dial_code": "+961", Id: "LB", Text: "LB"},
			{ "dial_code": "+266", Id: "LS", Text: "LS"},
			{ "dial_code": "+231", Id: "LR", Text: "LR"},
			{ "dial_code": "+218", Id: "LY", Text: "LY"},
			{ "dial_code": "+423", Id: "LI", Text: "LI"},
			{ "dial_code": "+370", Id: "LT", Text: "LT"},
			{ "dial_code": "+352", Id: "LU", Text: "LU"},
			{ "dial_code": "+853", Id: "MO", Text: "MO"},
			{ "dial_code": "+389", Id: "MK", Text: "MK"},
			{ "dial_code": "+261", Id: "MG", Text: "MG"},
			{ "dial_code": "+265", Id: "MW", Text: "MW"},
			{ "dial_code": "+60", Id: "MY", Text: "MY"},
			{ "dial_code": "+960", Id: "MV", Text: "MV"},
			{ "dial_code": "+223", Id: "ML", Text: "ML"},
			{ "dial_code": "+356", Id: "MT", Text: "MT"},
			{ "dial_code": "+692", Id: "MH", Text: "MH"},
			{ "dial_code": "+596", Id: "MQ", Text: "MQ"},
			{ "dial_code": "+222", Id: "MR", Text: "MR"},
			{ "dial_code": "+230", Id: "MU", Text: "MU"},
			{ "dial_code": "+262", Id: "YT", Text: "YT"},
			{ "dial_code": "+52", Id: "MX", Text: "MX"},
			{ "dial_code": "+691", Id: "FM", Text: "FM"},
			{ "dial_code": "+373", Id: "MD", Text: "MD"},
			{ "dial_code": "+377", Id: "MC", Text: "MC"},
			{ "dial_code": "+976", Id: "MN", Text: "MN"},
			{ "dial_code": "+382", Id: "ME", Text: "ME"},
			{ "dial_code": "+1664", Id: "MS", Text: "MS"},
			{ "dial_code": "+212", Id: "MA", Text: "MA"},
			{ "dial_code": "+258", Id: "MZ", Text: "MZ"},
			{ "dial_code": "+95", Id: "MM", Text: "MM"},
			{ "dial_code": "+264", Id: "NA", Text: "NA"},
			{ "dial_code": "+674", Id: "NR", Text: "NR"},
			{ "dial_code": "+977", Id: "NP", Text: "NP"},
			{ "dial_code": "+31", Id: "NL", Text: "NL"},
			{ "dial_code": "+599", Id: "AN", Text: "AN"},
			{ "dial_code": "+687", Id: "NC", Text: "NC"},
			{ "dial_code": "+64", Id: "NZ", Text: "NZ"},
			{ "dial_code": "+505", Id: "NI", Text: "NI"},
			{ "dial_code": "+227", Id: "NE", Text: "NE"},
			{ "dial_code": "+234", Id: "NG", Text: "NG"},
			{ "dial_code": "+683", Id: "NU", Text: "NU"},
			{ "dial_code": "+672", Id: "NF", Text: "NF"},
			{ "dial_code": "+1670", Id: "MP", Text: "MP"},
			{ "dial_code": "+47", Id: "NO", Text: "NO"},
			{ "dial_code": "+968", Id: "OM", Text: "OM"},
			{ "dial_code": "+92", Id: "PK", Text: "PK"},
			{ "dial_code": "+680", Id: "PW", Text: "PW"},
			{ "dial_code": "+970", Id: "PS", Text: "PS"},
			{ "dial_code": "+507", Id: "PA", Text: "PA"},
			{ "dial_code": "+675", Id: "PG", Text: "PG"},
			{ "dial_code": "+595", Id: "PY", Text: "PY"},
			{ "dial_code": "+51", Id: "PE", Text: "PE"},
			{ "dial_code": "+63", Id: "PH", Text: "PH"},
			{ "dial_code": "+64", Id: "PN", Text: "PN"},
			{ "dial_code": "+48", Id: "PL", Text: "PL"},
			{ "dial_code": "+351", Id: "PT", Text: "PT"},
			{ "dial_code": "+1939", Id: "PR", Text: "PR"},
			{ "dial_code": "+974", Id: "QA", Text: "QA"},
			{ "dial_code": "+40", Id: "RO", Text: "RO"},
			{ "dial_code": "+7", Id: "RU", Text: "RU"},
			{ "dial_code": "+250", Id: "RW", Text: "RW"},
			{ "dial_code": "+262", Id: "RE", Text: "RE"},
			{ "dial_code": "+590", Id: "BL", Text: "BL"},
			{ "dial_code": "+290", Id: "SH", Text: "SH"},
			{ "dial_code": "+1869", Id: "KN", Text: "KN"},
			{ "dial_code": "+1758", Id: "LC", Text: "LC"},
			{ "dial_code": "+590", Id: "MF", Text: "MF"},
			{ "dial_code": "+508", Id: "PM", Text: "PM"},
			{ "dial_code": "+1784", Id: "VC", Text: "VC"},
			{ "dial_code": "+685", Id: "WS", Text: "WS"},
			{ "dial_code": "+378", Id: "SM", Text: "SM"},
			{ "dial_code": "+239", Id: "ST", Text: "ST"},
			{ "dial_code": "+966", Id: "SA", Text: "SA"},
			{ "dial_code": "+221", Id: "SN", Text: "SN"},
			{ "dial_code": "+381", Id: "RS", Text: "RS"},
			{ "dial_code": "+248", Id: "SC", Text: "SC"},
			{ "dial_code": "+232", Id: "SL", Text: "SL"},
			{ "dial_code": "+65", Id: "SG", Text: "SG"},
			{ "dial_code": "+421", Id: "SK", Text: "SK"},
			{ "dial_code": "+386", Id: "SI", Text: "SI"},
			{ "dial_code": "+677", Id: "SB", Text: "SB"},
			{ "dial_code": "+252", Id: "SO", Text: "SO"},
			{ "dial_code": "+27", Id: "ZA", Text: "ZA"},
			{ "dial_code": "+211", Id: "SS", Text: "SS"},
			{ "dial_code": "+500", Id: "GS", Text: "GS"},
			{ "dial_code": "+34", Id: "ES", Text: "ES"},
			{ "dial_code": "+94", Id: "LK", Text: "LK"},
			{ "dial_code": "+249", Id: "SD", Text: "SD"},
			{ "dial_code": "+597", Id: "SR", Text: "SR"},
			{ "dial_code": "+47", Id: "SJ", Text: "SJ"},
			{ "dial_code": "+268", Id: "SZ", Text: "SZ"},
			{ "dial_code": "+46", Id: "SE", Text: "SE"},
			{ "dial_code": "+41", Id: "CH", Text: "CH"},
			{ "dial_code": "+963", Id: "SY", Text: "SY"},
			{ "dial_code": "+886", Id: "TW", Text: "TW"},
			{ "dial_code": "+992", Id: "TJ", Text: "TJ"},
			{ "dial_code": "+255", Id: "TZ", Text: "TZ"},
			{ "dial_code": "+66", Id: "TH", Text: "TH"},
			{ "dial_code": "+670", Id: "TL", Text: "TL"},
			{ "dial_code": "+228", Id: "TG", Text: "TG"},
			{ "dial_code": "+690", Id: "TK", Text: "TK"},
			{ "dial_code": "+676", Id: "TO", Text: "TO"},
			{ "dial_code": "+1868", Id: "TT", Text: "TT"},
			{ "dial_code": "+216", Id: "TN", Text: "TN"},
			{ "dial_code": "+90", Id: "TR", Text: "TR"},
			{ "dial_code": "+993", Id: "TM", Text: "TM"},
			{ "dial_code": "+1649", Id: "TC", Text: "TC"},
			{ "dial_code": "+688", Id: "TV", Text: "TV"},
			{ "dial_code": "+256", Id: "UG", Text: "UG"},
			{ "dial_code": "+380", Id: "UA", Text: "UA"},
			{ "dial_code": "+971", Id: "AE", Text: "AE"},
			{ "dial_code": "+44", Id: "GB", Text: "GB"},
			{ "dial_code": "+1", Id: "US", Text: "US"},
			{ "dial_code": "+598", Id: "UY", Text: "UY"},
			{ "dial_code": "+998", Id: "UZ", Text: "UZ"},
			{ "dial_code": "+678", Id: "VU", Text: "VU"},
			{ "dial_code": "+58", Id: "VE", Text: "VE"},
			{ "dial_code": "+84", Id: "VN", Text: "VN"},
			{ "dial_code": "+1284", Id: "VG", Text: "VG"},
			{ "dial_code": "+1340", Id: "VI", Text: "VI"},
			{ "dial_code": "+681", Id: "WF", Text: "WF"},
			{ "dial_code": "+967", Id: "YE", Text: "YE"},
			{ "dial_code": "+260", Id: "ZM", Text: "ZM"},
			{ "dial_code": "+263", Id: "ZW", Text: "ZW"}
		]

	},
	/**
	 * Il y a peut-être mieux, mais permet de gérer les boutons précédents / suivants du navigateur
	 * ---
	 * On fait une mise à jour du hash dans le navigateur
	 * Cela déclenche l'événement "hashchange" du navigateur
	 * Qui est défini dans App.vue et qui déclenche changeStepFromHash ci-dessous
	 * ---
	 * TODO : vérifier en conditions réelles
	 * @param {String} newStep
	 */
	changeStep(newStep) {
		window.location.hash = newStep
	},
	/**
	 * Modification réelle du "step" en cours
	 * @param {String} newStep
	 */
	changeStepFromHash(newStep) {
		this.state.step = newStep
		window.scrollTo(0, 0)
	}
}
